### ISSUE TITLE
Improve station depth 

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-profile-qaqc#20]
The reference station depth list present underestimates a number of stations and flag inappropriately some stations. 

We need to update the reference map at https://hakai.maps.arcgis.com/apps/webappviewer/index.html?id=38e1b1da8d16466bbe5d7c7a713d2678

And integrate that new reference file within the workflow. 

- [x] Apply new reference depth station to hakaidev database 
- [x] Apply new reference depth station to hakai production database

**Comment by JessyBarrette** [comment]
I already integrated the reference list developped by @ah-hakai 
[Hakai_CTD_stations_bathymetry_2022.csv](https://github.com/HakaiInstitute/hakai-profile-qaqc/files/10768839/Hakai_CTD_stations_bathymetry_2022.csv)

However with the most recent work from Will on the hakai map, we concluded it will be better to use the updated GIS map version again.

> Yes, I think that makes sense Jessy. Will's file has the data source indicated, plus it's accessible online. So that means Will is now the owner/manager of the official station depth list, and we can all draw from there. Updates/additions, etc. will come to Will if they happen. 

> I think you should use Will's updated 'Bot_depth_GIS' column - would you agree Will, that is better than using the WEST_COAST_DEM column? I think it's better to just have zeros everywhere right up against shore or intertidal, rather than try and put a number on water depth in those locations

**Comment by fostermh** [comment]
Nice to see this written up, thanks for doing that @JessyBarrette . @ah-hakai could you confirm you are getting alerts when mentioned in issues just so we know it is working for you?

**Comment by JessyBarrette** [comment]
related comments from @ah-hakai 
> 3. Incorrect station depth leading to inaccurate SVD flags (Jan. 26, 2023)
Problem: All scans at station DE1 were flagged SVD due to the cast depth (up to 435 m)
exceeding the expected cast depth of 239 m.
Action (Jan. 26, 2023): AH asked JB to (1) only flag those depths that exceed the expected
station depth (plus a buffer of 15%, already in use), and (2) use better bathymetry, such as
DFO’s NONNA 10 m bathymetry.

**Comment by ah-hakai** [comment]
Hi Matt.
Yes, I am getting notifications. In fact, there is even a link right in the
email subject line ('View Issue') that takes me right into GitHub and shows
the issue written up.

Thanks guys. I think this will be a more efficient way to engage with you
on these tasks.
Alex

**Comment by JessyBarrette** [comment]
Welcome to the github world @ah-hakai

**Comment by JessyBarrette** [comment]
This is a duplicated issue with #22. We'll close this issue.
