### ISSUE TITLE
Generate email once rebuild completed

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-profile-qaqc#28]
The present workfow applies occasionally a full rebuild of the CTD profiles flags on the hakaidev database in order to test and identify the different issues. 

Since this process is long (~4-5h) it would be good to have a script that generates an email to send to a list of email addresses once the process is completed. 

This email could also potentially contain a report or make it available somewhere online.

**Comment by JessyBarrette** [comment]
that's right it just triggers it and then disconnects right away for this specific case.

I was thinking of setting up a little email in Python to get sent with stmplib in python  https://docs.python.org/3/library/smtplib.html

I'm not sure if that's possible option with hakai's email system

**Comment by fostermh** [comment]
it's an option. we can discuss. I have done this for other applications.

**Comment by JessyBarrette** [comment]
I think I will just add a warning at the end of the code which will be capture by sentry and then can be send to Slack/email whatever. That's by far the simplest way to get an alarm :)

**Comment by JessyBarrette** [comment]
Any rebuild of the hakaidev or hakai database ctd qc flags now triggers a sentry warning.  We can close that issue.

Any rebuilds are also tracked on github through the environment deployments.
https://github.com/HakaiInstitute/hakai-profile-qaqc/deployments
