### ISSUE TITLE
Add flags declared within the processing stage into QARTOD

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-profile-qaqc#7]
# Issue
So issues with the data can't be detected once the data is processed that's why some of those flags were declared during the processing stage inside the process_log. Among there:
- No soak was detected
- Static measurement uses a too short stable time threshold

The Hakai CTD processing tool doesn't have the ability to send back flag columns. To go around this issue, the flags were included within the processing_log of the RBR processing tool.

Ideally those flags should make it to the Level1 and Level2 flags.

**Comment by rjbergerud** [comment]
So, we need `no_soak` and a `static_cast_too_short` level 1 & 2 flags in `ctd.ctd_cast`?  If so, I'll start tracking an issue in jira for this (though I like github issues, jira just to keep all my todos in one place)

**Comment by fostermh** [comment]
It seems to be this would be more of a single cast level flag which would indicate the whole cast is suspect because either there was no soak or the static cast was too short. this flag would apply to the whole cast or whole row of data, depending on where it was added, rather than to just one variable/channel as we have done with the other flags.

**Comment by JessyBarrette** [comment]
Yeah, you're right. Perhaps we can think if of a cast-level data quality flag that would handle the different causes. 
- location_flag: I think @rjbergerud  you had this already on your list
- processing_flag
    - No soak is detected.
    - We had to reduce the standard thresholds to execute the processing.
    - etc

Both may have a level 1 and level 2 flag column related to it.

The RBR processing tool can update the `processing_flag` based on the results. I don't see this being used by the seabird tool.
